-- TWO SEPARATE QUERY

SELECT CITY, LENGTH(CITY) AS NAME_LENGTH FROM STATION ORDER BY NAME_LENGTH, CITY LIMIT 1;

SELECT CITY, LENGTH(CITY) AS NAME_LENGTH FROM STATION ORDER BY NAME_LENGTH DESC, CITY LIMIT 1;

-- COMBINE INTO ONE QUERY

SELECT CITY, LENGTH(CITY) AS NAME_LENGTH FROM STATION ORDER BY NAME_LENGTH, CITY LIMIT 1 UNION ALL SELECT CITY, LENGTH(CITY) AS NAME_LENGTH FROM STATION ORDER BY NAME_LENGTH DESC, CITY LIMIT 1;